name: map_something
channels:
  - conda-forge
  - apple

dependencies:
  # base
  - python=3.10
  - pip
  - ipykernel
  - jupyterlab
  # base
  - pandas-stubs
  - sklearn
  - numpy
  - pandas
  - xarray
  - matplotlib
  - seaborn
  - sidecar
  - pyarrow
  - fastparquet
  - zarr
  # geo
  - geojson
  - shapely
  - geopandas
  - affine
  - rasterio
  - rioxarray
  - rio-cogeo
  - earthengine-api
  # leafmap
  - localtileserver
  - ipyleaflet
  - leafmap
  - fiona
  - flask = 2.3.3
  - geemap
  # lonboard
  - lonboard
  - pyogrio
  - requests
  - palettable
  - tqdm
  # tiles
  - fastapi
  - uvicorn
  - rio-tiler
  # clean-coding
  - pycodestyle
  - mypy
  # notes
  - mystmd
  - jupyterlab-myst
  - pytables
  - rich


######## INSTAL ENV FOR JUPYTER LAB ###################
#
# conda activate
# python -m ipykernel install --user --name map_something --display-name "Python (map_something)"
# jupyter lab .
#
#######################################################
