[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "map_something"
version = "0.0.1"
readme = "README.md"
dependencies = []

[tool.setuptools]
packages = [
	"map_something",
]